//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] apps {
            get {
                object obj = ResourceManager.GetObject("apps", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] autoruns {
            get {
                object obj = ResourceManager.GetObject("autoruns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0097FF.
        /// </summary>
        internal static string backgroundColor {
            get {
                return ResourceManager.GetString("backgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ccsetup416_slim {
            get {
                object obj = ResourceManager.GetObject("ccsetup416_slim", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CDDVDWin8_meta {
            get {
                object obj = ResourceManager.GetObject("CDDVDWin8_meta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RD /S /Q &quot;%UserProfile%\AppData\Local\Google\Chrome\User Data&quot;.
        /// </summary>
        internal static string fix_chrome {
            get {
                return ResourceManager.GetString("fix_chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firefox.exe -safe-mode.
        /// </summary>
        internal static string fix_firefox {
            get {
                return ResourceManager.GetString("fix_firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///powershell Set-ExecutionPolicy RemoteSigned
        ///ECHO If no errors are displayed, please press enter to continue.
        ///PAUSE
        ///powershell %temp%\reset-ie.ps1
        ///ECHO.
        ///ECHO Internet Explorer has been reset. Please restart the computer.
        ///ECHO.
        ///PAUSE.
        /// </summary>
        internal static string fix_ie {
            get {
                return ResourceManager.GetString("fix_ie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_Avast_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_Avast_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_Chrome_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_Chrome_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_Firefox_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_Firefox_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_iTunes_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_iTunes_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_Java_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_Java_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_LibreOffice_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_LibreOffice_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_Malwarebytes_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_Malwarebytes_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_OpenOffice_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_OpenOffice_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_Super_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_Super_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_Thunderbird_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_Thunderbird_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ninite_VLC_Installer {
            get {
                object obj = ResourceManager.GetObject("Ninite_VLC_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Norton_Removal_Tool {
            get {
                object obj = ResourceManager.GetObject("Norton_Removal_Tool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Office_2010_Remove {
            get {
                object obj = ResourceManager.GetObject("Office_2010_Remove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Office_2013_Removal {
            get {
                object obj = ResourceManager.GetObject("Office_2013_Removal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to net stop spooler
        ///del C:\windows\system32\spool\printers\*.* /q
        ///net start spooler.
        /// </summary>
        internal static string Printer_fix {
            get {
                return ResourceManager.GetString("Printer_fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Reset_Ie_Default {
            get {
                object obj = ResourceManager.GetObject("Reset_Ie_Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///COLOR 1F
        ///
        ///ECHO.
        ///ECHO Please note: this fix only works on Windows 8
        ///ECHO.
        ///ECHO Uninstalling KB2962407...
        ///wusa /uninstall /kb:2962407 /quiet /norestart
        ///ECHO.
        ///ECHO Update uninstalled. Please restart the computer, then open Windows Update and hide this update to prevent it from happening again
        ///ECHO.
        ///PAUSE.
        /// </summary>
        internal static string soundfix {
            get {
                return ResourceManager.GetString("soundfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon stormbolt {
            get {
                object obj = ResourceManager.GetObject("stormbolt", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///COLOR 1F
        ///
        ///ECHO.
        ///ECHO Please note: this fix only works on Windows 8
        ///ECHO.
        ///ECHO Uninstalling KB2871389...
        ///wusa /uninstall /kb:2871389 /quiet /norestart
        ///ECHO.
        ///ECHO Update uninstalled. Please restart the computer, then try the Windows 8.1 upgrade again.
        ///ECHO.
        ///PAUSE.
        /// </summary>
        internal static string win81adminfix {
            get {
                return ResourceManager.GetString("win81adminfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string winupdatebat {
            get {
                return ResourceManager.GetString("winupdatebat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///COLOR 1F
        ///
        ///:: Version 1.7
        ///:: Feature List
        ///:: A menu interface designed for techs who multi-task.
        ///::    - (done) appears by completed tasks.
        ///::    - All events have notes on what is happening and why.
        ///:: Run Windows Update Troubleshooter
        ///::    - msdt version builtin
        ///::    - doesn&apos;t ask for further options at finish
        ///:: Shut down update-related services
        ///::    - wuauserv, bits, appidsvc, cryptosvc
        ///:: Rename SoftwareDistribution
        ///::    - intelligent rename, deletes target if exist
        ///::    -  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WinUpdateFix {
            get {
                return ResourceManager.GetString("WinUpdateFix", resourceCulture);
            }
        }
    }
}
